platform :ios, '10.0'

target 'GroceryList' do
  use_frameworks!
  inhibit_all_warnings!
  
  # Pods for GroceryList
  pod 'RxSwift', '~> 4.2'
  pod 'RxCocoa', '~> 4.2'

  target 'GroceryListTests' do
    inherit! :search_paths
    pod 'GCDWebServer', '~> 3.4.2'
    pod 'RxBlocking', '~> 4.2'
    pod 'RxTest', '~> 4.2'
  end

end
